raar:
  url: https://archiv.rabe.ch/api
  username:
  password:
  options:
    verify_ssl: 0 # OpenSSL::SSL::VERIFY_NONE

shows:
  info:
    feed_url: http://rabe.ch/broadcast/info/feed/
    filter: .//category[text()='Podcasts & Playlists']
    raar_id: 11

importer:
  log_level: info
  log: syslog
